<template>
     <div class="container">
        <div class="table table-container">
            <thead>
                <tr>
                    <th v-for="column, index in view_columns" :key="column">
                        <span>{{ column }}</span>

                        <div class="column-controls">
                            <span @click="column_toggle_sort(index)" class="icon is-small">
                                <i v-if="sort.index == index &amp;&amp; sort.desc" class="fa fa-sort-desc"></i>
                                <i v-else-if="sort.index == index &amp;&amp; !sort.desc" class="fa fa-sort-asc"></i>
                                <i v-else class="fa fa-sort"></i>
                            </span>
                        </div>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="row,indexR in view_data" :key="indexR">
                    <td  @click="onClick(row)" v-for="column,indexC in row" :key="indexC">
                        {{ column }}

                    </td>
                </tr>

                <tr v-if="view_data.length == 0">
                    <td :colspan="view_columns.length" class="has-text-centered">No data specified.</td>
                </tr>
            </tbody>
        </div>
    </div>
</template>

<script>
import _ from 'lodash'
export default {
    name:'table',
    props: ['data', 'columns', 'query', 'controls_column'],
    data () {
        return {
        view_columns: [],
        view_data: [],
        data_map: {},
        slot_map: {},
        sort: {
            index: 0,
            desc: true
        }
    }
  },
  methods: {
    parse_columns() {
      this.columns.forEach((column, index) => {
        if (typeof(column) == 'string') {
          return this.view_columns.push(column);
        }

        this.view_columns.push(column[0]);

        if (column[1].startsWith('!')) {
          // This is a slot.

        } else if (column.length > 1) {
          // So this would make a map like { column_index: field }
          this.data_map[index] = column[1];
        }
      });
    },
    column_toggle_sort(column_index) {
      if (column_index == this.sort.index) {
        this.sort.desc = !this.sort.desc;
      } else {
        this.sort.index = column_index;
        this.sort.desc = true;
      }

      this.sort_data();
    },
    parse_data() {
      if (this.data == undefined) {
        return;
      }

      this.view_data = [];

      this.data.forEach((row_object, index) => {
        let row = [];

        // Assume an object if the data_map is set. Otherwise parse as a straight array.
        if (Object.keys(this.data_map).length > 0 && index < (Object.keys(this.data_map).length-1) ) {
          Object.keys(this.data_map).forEach((key) => {
            let value = this.data_map[key];

            if (value in row_object ) {
              row.push(row_object[value]); 
            }
          });
        } else {
          row = row_object;
        }

        // Filter if a query is provided.
        if (typeof(this.query) !== "undefined" && this.query !== "") {
          let matched = false;

          row.forEach((cell) => {
            let query = String(this.query).toLowerCase().trim();

            if (String(cell).toLowerCase().indexOf(query) !== -1) {
              matched = true;
            }
          });

          if (matched) {
            this.view_data.push(row);
          }
        } else {
          this.view_data.push(row);
        }
      });

    },
    sort_data() {
      this.view_data = _.sortBy(this.view_data, [(row) => {
        if (row[this.sort.index] == "None") {
          return 0;
        }

        let sizes = ['KB','MB','GB','TB'];
        let regex = RegExp('^([0-9\\.]+)\\s?(' + sizes.join('|') + ')', 'ig')
        let matches = regex.exec(row[this.sort.index]);

        if (matches) {
          return Math.pow(1024, _.indexOf(sizes, matches[2])) * parseFloat(matches[1]);
        }

        return row[this.sort.index];
      }]);

      if (!this.sort.desc) {
        this.view_data.reverse();
      }
    },
    onClick(data){
        this.$emit('update', data)
    }
  },
  created() {
    this.parse_columns()
    this.parse_data()
    this.sort_data()
  },
  watch: {
    query() {
      this.parse_data()
      this.sort_data()
    }
  }
}
</script>

<style>
/*! bulma.io v0.9.2 | MIT License | github.com/jgthms/bulma */
/*! Generated by Bulma Customizer v0.2.0 | https://github.com/webmasterish/bulma-customizer */
.table-container:not(:last-child), .table:not(:last-child) {
    margin-bottom: 1.5rem;
  }
  
  .table {
    font-size: 15px;
    background-color: white;
    color: #363636;
  }
  .table td,
  .table th {
    font-size: 15px;
    border: 1px solid #dbdbdb;
    border-width: 0 0 1px;
    padding: 0.5em 0.75em;
    vertical-align: top;
  }

  .table tbody tr:hover {
    background-color: #00d1b2;
    cursor: pointer
  }

  .table thead th:hover{
    background-color: white ;
  }

  .table td.is-white,
  .table th.is-white {
    background-color: white;
    border-color: white;
    color: #0a0a0a;
  }
  .table td.is-black,
  .table th.is-black {
    background-color: #0a0a0a;
    border-color: #0a0a0a;
    color: white;
  }
  .table td.is-light,
  .table th.is-light {
    background-color: whitesmoke;
    border-color: whitesmoke;
    color: rgba(0, 0, 0, 0.7);
  }
  .table td.is-dark,
  .table th.is-dark {
    background-color: #363636;
    border-color: #363636;
    color: #fff;
  }
  .table td.is-primary,
  .table th.is-primary {
    background-color: #00d1b2;
    border-color: #00d1b2;
    color: #fff;
  }
  .table td.is-link,
  .table th.is-link {
    background-color: #485fc7;
    border-color: #485fc7;
    color: #fff;
  }
  .table td.is-info,
  .table th.is-info {
    background-color: #3e8ed0;
    border-color: #3e8ed0;
    color: #fff;
  }
  .table td.is-success,
  .table th.is-success {
    background-color: #48c78e;
    border-color: #48c78e;
    color: #fff;
  }
  .table td.is-warning,
  .table th.is-warning {
    background-color: #ffe08a;
    border-color: #ffe08a;
    color: rgba(0, 0, 0, 0.7);
  }
  .table td.is-danger,
  .table th.is-danger {
    background-color: #f14668;
    border-color: #f14668;
    color: #fff;
  }
  .table td.is-narrow,
  .table th.is-narrow {
    white-space: nowrap;
    width: 1%;
  }
  .table td.is-selected,
  .table th.is-selected {
    background-color: #00d1b2;
    color: #fff;
  }
  .table td.is-selected a,
  .table td.is-selected strong,
  .table th.is-selected a,
  .table th.is-selected strong {
    color: currentColor;
  }
  .table td.is-vcentered,
  .table th.is-vcentered {
    vertical-align: middle;
  }
  .table th {
    color: #363636;
  }
  .table th:not([align]) {
    text-align: inherit;
  }
  .table tr.is-selected {
    background-color: #00d1b2;
    color: #fff;
  }
  .table tr.is-selected a,
  .table tr.is-selected strong {
    color: currentColor;
  }
  .table tr.is-selected td,
  .table tr.is-selected th {
    border-color: #fff;
    color: currentColor;
  }
  .table thead {
    background-color: transparent;
  }
  .table thead td,
  .table thead th {
    border-width: 0 0 2px;
    color: #363636;
  }
  .table tfoot {
    background-color: transparent;
  }
  .table tfoot td,
  .table tfoot th {
    border-width: 2px 0 0;
    color: #363636;
  }
  .table tbody {
    background-color: transparent;
  }
  .table tbody tr:last-child td,
  .table tbody tr:last-child th {
    border-bottom-width: 0;
  }
  .table.is-bordered td,
  .table.is-bordered th {
    border-width: 1px;
  }
  .table.is-bordered tr:last-child td,
  .table.is-bordered tr:last-child th {
    border-bottom-width: 1px;
  }
  .table.is-fullwidth {
    width: 100%;
  }
  .table.is-hoverable tbody tr:not(.is-selected):hover {
    background-color: #fafafa;
  }
  .table.is-hoverable.is-striped tbody tr:not(.is-selected):hover {
    background-color: #fafafa;
  }
  .table.is-hoverable.is-striped tbody tr:not(.is-selected):hover:nth-child(even) {
    background-color: whitesmoke;
  }
  .table.is-narrow td,
  .table.is-narrow th {
    padding: 0.25em 0.5em;
  }
  .table.is-striped tbody tr:not(.is-selected):nth-child(even) {
    background-color: #fafafa;
  }
  
  .table-container {
    font-size: 15px;
    -webkit-overflow-scrolling: touch;
    overflow: auto;
    overflow-y: hidden;
    max-width: 100%;
  }

  /*! bulma.io v0.9.2 | MIT License | github.com/jgthms/bulma */
/*! Generated by Bulma Customizer v0.2.0 | https://github.com/webmasterish/bulma-customizer */
.container {
  flex-grow: 1;
  margin: 0 auto;
  position: relative;
  width: auto;
}
.container.is-fluid {
  max-width: none !important;
  padding-left: 32px;
  padding-right: 32px;
  width: 100%;
}
@media screen and (min-width: 1024px) {
  .container {
    max-width: 960px;
  }
}
@media screen and (max-width: 1215px) {
  .container.is-widescreen:not(.is-max-desktop) {
    max-width: 1152px;
  }
}
@media screen and (max-width: 1407px) {
  .container.is-fullhd:not(.is-max-desktop):not(.is-max-widescreen) {
    max-width: 1344px;
  }
}
@media screen and (min-width: 1216px) {
  .container:not(.is-max-desktop) {
    max-width: 1152px;
  }
}
@media screen and (min-width: 1408px) {
  .container:not(.is-max-desktop):not(.is-max-widescreen) {
    max-width: 1344px;
  }
}
</style>
